api:
  dashboard: true

entryPoints:
  web:
    address: :80

  websecure:
    address: :443
    http:
      tls:
        certResolver: letsencrypt

  diskstation:
    address: :5001
    http:
      tls:
        certResolver: letsencrypt

  cloudstation:
    address: :6690

  git:
    address: :7999


providers:
  file:
    directory: /etc/traefik/fileconfig
    watch: true

log:
  filePath: "/var/log/traefik.log"
  level: DEBUG

certificatesResolvers:
  letsencrypt:
    acme:
      email: mquarg@gmx.de
      storage: /etc/traefik/certs/acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web  
